#!/bin/sh

for f in *_test.c
do
	${CC:-gcc} -g -fsanitize=address -fsanitize=undefined -Wall -Wpedantic -Wextra -Werror -o "$f.out" "$f" || exit 1
	echo "$f:"
	./$f.out || exit 1
	rm "$f.out"
	printf "\n"
done

echo "PASS"
